---
title: "Collecting Data from Reddit-Youtube"
author: "Ahmet Kurnaz"
date: "01 06 2021"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,eval = F)
```

## Outline

- Reddit Data
- Youtube Data


## Reddit Data with RSelenium

```{r red}

require(RSelenium)
require(rvest)

rD <- rsDriver(browser = c("firefox"),port = 4445L)
remDr <- rD$client

remDr$navigate('https://www.reddit.com/r/news/comments/np9m8k/naomi_osaka_withdrew_from_the_french_open_on/')


full_discussion_button <- remDr$findElement('xpath','/html/body/div[1]/div/div[2]/div[2]/div/div[3]/div[1]/div[2]/div[6]/div/button')

full_discussion_button$clickElement()



for(i in 1:3){
    body <- remDr$findElement("css", "body")

    body$sendKeysToElement(list(key = "end"))
  
  
  for(j in 1:110){
    body$sendKeysToElement(list(key = "up_arrow"))  
  }
  

    more_comments_link <- remDr$findElement('css','._2HYsucNpMdUpYlGBMviq8M')


  more_comments_link$clickElement()


  cur_sleep <- sample(4:6,1)
  message('Sleep: ',cur_sleep)
  Sys.sleep(cur_sleep)
}


reddit_page <- read_html(remDr$getPageSource()[[1]])

reddit_divs <- reddit_page%>%html_nodes('div')
reddit_divs_attrs <- reddit_divs%>%html_attr('data-test-id')

div_indices <- sapply(reddit_divs_attrs,function(x){
  if(is.na(x)){
    return(F)
  }else if(x=='comment'){
    return(T)
  }else{
    return(F)
  }
})



comment_divs <- reddit_divs[div_indices]

comment_text <- comment_divs%>%html_text()

rD$server$stop()

```

## YouTube Data with YouTube Data API

- YouTube Data API: [here](https://developers.google.com/youtube/v3/docs)


```{r you}

require(tuber)

yt_oauth(app_id = '541390500149-3mpqm9509ellh9safmnjnu1melp1uqa5.apps.googleusercontent.com',app_secret = '1ZFV6Jc0IdAcEgGw6tKQMHkM',token = '')


get_stats(video_id="N708P-A45D0")



get_video_details(video_id="N708P-A45D0")



res <- get_comment_threads(c(video_id="N708P-A45D0"))
head(res)
```


