---
title: "Data Wrangling"
author: "Ahmet Kurnaz"
date: "08 06 2021"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,eval = F)
```

## Outline

 - tidyverse
 - data.table
 - lubridate
 
## Let's Get Data

 - Data Source: [here](https://www.kaggle.com/preetviradiya/imdb-movies-ratings-details)

```{r read_data}

movie_data <- read.csv('IMDB_movie_reviews_details.csv',header = T,encoding = 'UTF-8')


```
 
## tidyverse

 - [website](https://www.tidyverse.org/packages/)

```{r tidy_chunk}

library(tidyverse)

movie_data_tibble <- as.tibble(movie_data)

movie_data_tibble <- movie_data_tibble%>%select(-X)

fav_movies <- movie_data_tibble%>%filter(rating>=9)

yearly_counts <- movie_data_tibble%>%count(year)

yearly_counts%>%arrange(-n)


```


## data.table

  - [website](https://rdatatable.gitlab.io/data.table/)
  
  
```{r dt_chunk}
library(data.table)
movie_data_dt <- fread('IMDB_movie_reviews_details.csv',encoding = 'UTF-8',header = T)

movie_data_dt <- movie_data_dt[,.SD,.SDcols= -'V1']

movie_data_dt[,.N,by=year]

movie_data_dt[,.N,by=year][order(-N)]


movie_data_dt[,.N,by=c('year','rating')]


movie_data_dt[year>=2000]

movie_data_dt[genre %like%'Drama']

movie_data_dt[,is_drama:=0]
movie_data_dt[genre %like%'Drama',is_drama:=1]

genres <-  movie_data_dt[!duplicated(genre),genre]

genres <- sapply(genres,function(x){
  g <- str_split(string = x,pattern=',',simplify = T)
  return(g)
})

genres <- unlist(genres)
genres <- unique(genres)

genres <- str_trim(genres,'both')

for(i in 1:length(genres)){
  
  message('Genre: ',genres[i])
  cur_genre_name <- paste0('is',genres[i])
  movie_data_dt[,eval(cur_genre_name):=0]
  movie_data_dt[genre%like%genres[i],eval(cur_genre_name):=1]
  
}


movie_data_dt[,gross:=gsub('M','',gross)]
movie_data_dt[,gross:=gsub('\\$','',gross)]
movie_data_dt[gross=='',gross:=NA]
movie_data_dt[,gross:=as.double(gross)]

setnames(movie_data_dt,'gross','gross(M)')


movie_data_dt[isAction==1&!is.na(`gross(M)`)][order(-rating),.(name,year,`gross(M)`)]


action_movies <- movie_data_dt[isAction==1]

cor(action_movies$`gross(M)`,action_movies$rating,use = 'pairwise.complete.obs',method = 'pearson')

```

## short comparison

```{r comp}

object.size(movie_data)
object.size(movie_data_tibble)
object.size(movie_data_dt)

```

## lubridate

 - data source: [here](https://www.kaggle.com/sureshmecad/mens-shoe-prices)
 
```{r lub}
library(lubridate)
shoe_data <- fread('train.csv')

shoe_data <- shoe_data[,.(brand,dateadded,dateupdated,prices_dateadded,prices_dateseen)]


shoe_data[,date_added:=ymd_hms(dateadded)]

shoe_data[month(date_added)<6]

shoe_data[,.N,by=week(date_added)][order(week)]

shoe_data[,date_update:=ymd_hms(dateupdated)]

shoe_data[,intrvl:=interval(date_added,date_update)/days(1)]

```
