---
title: "Clustering Scripts"
date: "SICSS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading the Google Sheets data

Hello everyone! If you are going to be conducting Research Speed Dating, please make sure to change the sheet name on line 25: `dat <- read_sheet(ss, sheet = "INSERT LOCATION NAME")`. Your location tab can be located at the bottom of this Google Sheet: https://tinyurl.com/SICSSSpeedDating2021 


```{r, message = FALSE, echo=FALSE, warning = FALSE, error = FALSE}
library(googlesheets4)
library(janitor)
library(naniar)
library(tidyverse)
gs4_deauth()
#link
ss <- "https://docs.google.com/spreadsheets/d/1Uoe_dw5ZY54AdLIHWNn4UO-wS2J_4UAc_SGeYa5C2gs/edit?usp=sharing"
#organizers, change the sheet name to your specific site here:
dat <- read_sheet(ss, sheet = "Sample")
#clean variable names
dat <- clean_names(dat)
dat <- dat %>% filter(name != "SAMPLE STUDENT")
#select variables needed for group creation
dat <- dat %>% select(-c(email))
#replace NAs with 0s
dat <- dat %>% replace(is.na(.), 0)

#glimpse(dat)
```  

# Identifying maximally similar groups  

```{r, echo = FALSE, message = FALSE, warning = FALSE, error = FALSE}
#create distance matrix
dat_mat <- as.matrix(dat)
rownames(dat_mat) <- dat$name
dat_mat <- dat_mat[,-1]
dmatrix <- dist(dat_mat, method = "euclidean") 

#fit with the hierarchical clustering
fit <- hclust(dmatrix, method="ward.D") 

# display dendogram
plot(fit) 
groups <- cutree(fit, k=5) # cut tree into 5 clusters

# draw dendogram with cut points for groups 
rect.hclust(fit, k=5, border="red")
```


# Identifying maximally disimilar groups  

```{r, eval=TRUE, echo = FALSE}
#identifying maximally dissimilar
final<-as.data.frame(NULL)
dat$names<-NULL
library(dplyr)
library(vegan)

for (i in 1:1000){
  test<-sample_n(dat, 4)
  names<-paste(test$name, collapse=",")
  diversity_score<-diversity(unlist(test[,c(2:ncol(test))]))
  data<-cbind(names, diversity_score)
  final<-rbind(final, data)
  if(1000 %% i == 0){
   print(i) 
  }
}
```


```{r, eval=TRUE, echo = FALSE}
#organizers, people may be assigned to more than one group 
#they should choose or you should assign them to one 
final$diversity_score<-as.character(final$diversity_score)
final$diversity_score<-as.numeric(final$diversity_score)
final<-final[order(final$diversity_score, decreasing=TRUE),]
head(final, 10)

```


