---
title: "Introduction to Automated Text Analysis"
subtitle: "Group Exercise"
author: Carsten Schwemmer
date: 2023-07-26
date-format: "DD.MM.YYYY"
format: 
  html:
    code-fold: show
    self-contained: true
    theme: spacelab
    highlight-style: atom-one
  revealjs:
    smaller: true
    code-fold: show
    self-contained: true
execute:
  echo: true
editor: visual
---

Today we covered a broad range of techniques for analyzing texts based upon bag-of-words approaches. For today's exercise, there are two options among which you can choose:

-   a more structured group exercise using the *TED Talks* dataset

-   a "freestyle" exercise using the *DonorsChoose* dataset

You can make this choice after dividing yourselves into groups of four.

## Option 1 - TED Talks (structured)

1)  Load the dataframe of TED talks that we analyzed with dictionaries earlier today

2)  Use at least two of the techniques we discussed this morning to pull out features from the talk transcripts (e.g. substantive themes, topics, sentiment). Analyze to what extent the content of TED talk varies by speaker sex

3)  Merge the dataframe with corresponding YouTube metadata `tedtalks_transcripts_meta.csv`. For each video of a TED talk, this dataset includes popularity metrics - such as likes and views at the time of data collection - as well as the average sentiment scores of corresponding comments (see [here](https://www.tandfonline.com/doi/full/10.1080/2474736X.2019.1646102){target="_blank"} for more details)

4)  Work together to identify whether any textual features and / or speaker attributes are useful for predicting popularity metrics and / or comment sentiment scores on YouTube

## Option 2 - DonorsChooose (unstructured)

Use the DonorsChoose dataset `donors_choose_sample.csv` to apply any of the techniques we discussed today. Examples of questions you might ask:

-   how has classroom technology use changed over time? How does it differ by geographic location and the age of students?
-   how do the requests of schools in urban areas compare to those in rural areas?
-   what predicts whether a project will be funded?
-   how do the predictors of funding success vary by geographic location? Or by economic status of the students?

## Share your findings

-   regardless which exercise option you have chosen, produce one visualization that describes the main findings of your analysis
-   the visualization should be as self-explanatory as possible, e.g. by including figure title, subtitle, and additional notes
-   share your visualization on Slack until 3.45 PM
